{% set data = load_setup_py_data() %}

package:
  name: anaconda-anon-usage
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python  # [not win]
  script_env:
   - NEED_SCRIPTS=no   # [variant=="plugin"]
   - NEED_SCRIPTS=yes  # [variant=="patch"]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - conda>=23.7  # [variant=="plugin"]
    - conda>=22.11,<23.7   # [variant=="patch"]

test:
  source_files:
    - tests
  commands:
    - export ANACONDA_ANON_USAGE_DEBUG=1  # [unix]
    - set ANACONDA_ANON_USAGE_DEBUG=1  # [win]
    - conda info
    - python -m anaconda_anon_usage.install --status  # [variant=="patch"]
    - python tests/test_config.py

about:
  home: https://github.com/Anaconda-Platform/anaconda-anon-usage
  summary: basic anonymous telemetry for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
